#!/bin/python

import urllib.request, json

city = "792680"
api_key = "958a2d3e8641a8268d79632faaf7a762" 

weather = eval(str(urllib.request.urlopen("http://api.openweathermap.org/data/2.5/weather?id={}&appid={}".format(city, api_key)).read())[2:-1])

info = weather["weather"][0]["description"].capitalize()
temp = int(float(weather["main"]["temp"]) - 272.15)

print("%s, %i °C" % (info, temp))