#! /bin/sh

sxhkd &


bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config normal_border_color "#1b1b1b"
bspc config focused_border_color "#181818"
#bspc config normal_border_color "#1f1f1f"
#bspc config focused_border_color "#1f1f1f"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^1'
bspc rule -a mpv desktop='^3' follow=on
bspc rule -a VirtualBox desktop='^7'
bspc rule -a "VirtualBox Manager" desktop='^7'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


compton &
sh ~/.fehbg &
$HOME/.config/polybar/launch.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xsetroot -cursor_name left_ptr
redshift -l 44.7:20.4 -t 5700:4000 &
