#! /bin/sh

sxhkd &


bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config normal_border_color "#1f1f1f"
bspc config focused_border_color "#1f1f1f"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mpv desktop='^3' follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


compton &
sh ~/.fehbg &
$HOME/.config/polybar/launch.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xsetroot -cursor_name left_ptr
